# Generated by Django 2.1.7 on 2019-02-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0002_auto_20190214_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='subject',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
