# Generated by Django 2.1.7 on 2019-02-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0003_list_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='item',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='completed',
            new_name='isCompleted',
        ),
    ]
